-- DOOM 2016 / idTech6 CONFIG example for the universal RAW provider.
--
-- The provider remains math-free. For idTech6 the RAW rotation triplet is
-- repurposed to carry the native Forward vector. IGCSRelay reconstructs the
-- orthonormal Right / Up / Forward basis.

local CONFIG = {

  engine = "idTech6",

  bases = {
    position = "pCamera",
    rotation = "pCamera",
    fov      = ""
  },

  position = {
    x = 0x000,
    y = 0x004,
    z = 0x008
  },

  -- idTech6 mapping:
  -- pitch slot = Forward X
  -- yaw   slot = Forward Y
  -- roll  slot = Forward Z
  rotation = {
    pitch = 0x5A4,
    yaw   = 0x5A8,
    roll  = 0x5AC
  },

  -- Temporary until the real DOOM 2016 Photo Mode FOV address is validated.
  fov = {
    fixed = 45.0
  },

  cameraLockSymbol = "",
  writers = {},

  restoreHoldMs = 250,
  cameraIntervalMs = 16
}

-- Validated behavior:
--   * no camera pointer lock
--   * no writer NOPs
--   * native Forward at pCamera + 0x5A4 / 0x5A8 / 0x5AC
--   * multishot movement generated by Relay in camera Right / Up plane
--   * idTech6 DOOM bokeh scale = 2.0
--
-- Not yet implemented / validated:
--   * real Photo Mode FOV address
--   * native roll
--   * panorama yaw for the Forward-vector RAW packing
