name: Build IGCS Relay

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build x86 and x64
        shell: cmd
        run: scripts\Setup-All.cmd

      - name: Upload IGCS Relay
        uses: actions/upload-artifact@v4
        with:
          name: IGCSRelay
          path: |
            build/vs2022-x86/bin/Release/IGCSRelay.addon32
            build/vs2022-x64/bin/Release/IGCSRelay.addon64
          if-no-files-found: error
